export const FETCH_TOKEN_START = 'FETCH_TOKEN_START';
export const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS';
export const FETCH_TOKEN_FAILURE = 'FETCH_TOKEN_FAILURE';

export const USER_AUTH = 'USER_AUTH';

export const TOGGLE_FILTER = 'TOGGLE_FILTER';

export const FETCH_JOGS_START = 'FETCH_JOGS_START';
export const FETCH_JOGS_SUCCESS = 'FETCH_JOGS_SUCCESS';
export const FETCH_JOGS_FAILURE = 'FETCH_JOGS_FAILURE';